// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAlMkzmPJ1ZwM1Hg1dEC0hX60DbtdnVI6U',
    appId: '1:447835740010:web:d76764b8b72241ef70f713',
    messagingSenderId: '447835740010',
    projectId: 'eco-market-b8cea',
    authDomain: 'eco-market-b8cea.firebaseapp.com',
    storageBucket: 'eco-market-b8cea.firebasestorage.app',
    measurementId: 'G-KPXMW89HEJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAdXQFuZ7dcdYyyjeufc-DLe29u_W1OlsY',
    appId: '1:447835740010:android:93d8811f6852b40d70f713',
    messagingSenderId: '447835740010',
    projectId: 'eco-market-b8cea',
    storageBucket: 'eco-market-b8cea.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA6ZdVC-sYA3_BJKLQWE26KtVlDbGjU2kI',
    appId: '1:447835740010:ios:a06b0ee6b9fcfda170f713',
    messagingSenderId: '447835740010',
    projectId: 'eco-market-b8cea',
    storageBucket: 'eco-market-b8cea.firebasestorage.app',
    iosBundleId: 'com.example.flutterEcomarket1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA6ZdVC-sYA3_BJKLQWE26KtVlDbGjU2kI',
    appId: '1:447835740010:ios:a06b0ee6b9fcfda170f713',
    messagingSenderId: '447835740010',
    projectId: 'eco-market-b8cea',
    storageBucket: 'eco-market-b8cea.firebasestorage.app',
    iosBundleId: 'com.example.flutterEcomarket1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAlMkzmPJ1ZwM1Hg1dEC0hX60DbtdnVI6U',
    appId: '1:447835740010:web:6f5a2b02e7653bee70f713',
    messagingSenderId: '447835740010',
    projectId: 'eco-market-b8cea',
    authDomain: 'eco-market-b8cea.firebaseapp.com',
    storageBucket: 'eco-market-b8cea.firebasestorage.app',
    measurementId: 'G-GDQLV4QHW2',
  );
}
